app:
  database:
    path: ${user.home}/magazzino.db

spring:
  application:
    name: Magazzino
  datasource:
    url: jdbc:sqlite:${app.database.path}
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 8080
  shutdown: graceful
logging:
  file:
    name: ${user.home}/magazzino.log
  level:
    root: INFO